version: '3'

networks:
  backend:
  frontend:

services:

### reverse-proxy #########################################
  reverse:
    container_name: reverse
    networks:
      - frontend
      - backend
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/reverse-proxy/conf.d:/etc/nginx/conf.d
      - ../../:/usr/share/nginx/html
      - ./nginx/log/error.log:/var/log/nginx/error.log

### node #########################################
  webserver:
    container_name: webserver
    networks:
      - frontend
      - backend
    image: node:14.15.3
    expose:
      - 8080
    working_dir: '/usr/share/nginx/html/kingdom/'
    command: "npm run serve"
    volumes:
      - ./node/log/error.log:/var/log/node/error.log
      - ../:/usr/share/nginx/html/kingdom

  node:
    container_name: node
    networks:
      - frontend
      - backend
    restart: always
    image: node:14.15.3
    ports:
      - "3000:3000"
    working_dir: '/usr/share/nginx/html/kingdom/'
    command: "node server.js"
    volumes:
      - ./node/log/error.log:/var/log/node/error.log
      - ../:/usr/share/nginx/html/kingdom



